const INCREMENT_UI_SUCCESS = 'INCREMENT_UI_SUCCESS';
const DECREMENT_UI_SUCCESS = 'DECREMENT_UI_SUCCESS';
const UPDATE_UI_SUCCESS = 'UPDATE_UI_SUCCESS';
export default {
  INCREMENT_UI_SUCCESS,
  DECREMENT_UI_SUCCESS,
  UPDATE_UI_SUCCESS
};
